name: personal_portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  icons_launcher: ^2.1.7

icons_launcher:
  image_path: "assets/images/myself.png"
  platforms:
    android:
      enable: true
      image_path: "assets/images/myself.png"
    ios:
      enable: true
      image_path: "assets/images/myself.png"
    web:
      enable: true
      image_path: "assets/images/myself.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf